[package]
name = "pogo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
postgres = "0.19.2"
prettytable-rs = "0.8.0"
